import {bez,plen} from './geo.js';
const rnd=(s=>()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296})(7);
const pick=a=>a[Math.floor(rnd()*a.length)];
export const ZONES={'Anna Nagar':[13.085,80.21],Kilpauk:[13.083,80.243],Nungambakkam:[13.061,80.242],'T. Nagar':[13.041,80.234],Guindy:[13.007,80.221],Adyar:[13.006,80.257],Velachery:[12.975,80.221],OMR:[12.9,80.228],Mylapore:[13.033,80.269],Porur:[13.038,80.157],Tambaram:[12.925,80.1]};
export const ZN=Object.keys(ZONES);
export const CIRCLES=['Friends','College','Company','Apartment','Team'];
export const ROUTE_KS=[.08,.22,-.2,.14];
export const NOW=Math.floor(Date.now()/60000);
const FN=['Aarav','Divya','Karthik','Meena','Suresh','Priya','Vikram','Lakshmi','Arjun','Nisha','Rahul','Kavya','Sanjay','Deepa','Naveen','Anita'],LN=['Raman','Iyer','Kumar','Nair','Pillai','Babu','Sekar','Menon','Rao','Gopal'];
export const communities=Array.from({length:55},(_,i)=>({id:'c'+i,type:CIRCLES[i%5],name:`${CIRCLES[i%5]} group ${Math.floor(i/5)+1}`}));
const FR=['Ananya S','Rohan M','Sneha K','Imran A','Harini V','Dev P','Kiran R','Tara N'];
export const users=Array.from({length:160},(_,i)=>({id:'u'+i,name:i===0?'You (Demo)':i<=8?FR[i-1]:`${pick(FN)} ${pick(LN)}`,circles:i===0?['Friends','College']:i<=8?['Friends','College']:[pick(CIRCLES),pick(CIRCLES)],home:pick(ZN),demo:true}));
export const friends=users.slice(1,9);
export const vehicles=Array.from({length:130},(_,i)=>({id:'v'+i,seats:pick([3,4,4,5,6]),model:pick(['Hatchback','Sedan','SUV','Compact SUV'])}));
export const drivers=Array.from({length:84},(_,i)=>{const u=users[20+i%140];return{id:'d'+i,userId:u.id,name:u.name,circles:i%3===0?['College','Company']:u.circles,rating:+(3.9+rnd()*1.1).toFixed(1),trips:Math.floor(20+rnd()*380),cancel:+(rnd()*.08).toFixed(3),idv:rnd()>.05,drv:rnd()>.06,veh:rnd()>.08,vehicle:vehicles[i]}});
const jit=z=>[z[0]+(rnd()-.5)*.008,z[1]+(rnd()-.5)*.008];
export const routes=Array.from({length:120},(_,i)=>({id:'r'+i,k:ROUTE_KS[i%4]}));
export const journeys=Array.from({length:270},(_,i)=>{const hot=i<48;const from=hot?'Anna Nagar':pick(ZN);let to=hot?pick(['Guindy','Guindy','Guindy','T. Nagar']):pick(ZN);if(to===from)to='Guindy';const d=drivers[i%84],a=jit(ZONES[from]),b=jit(ZONES[to]),k=ROUTE_KS[i%4],pts=bez(a,b,k),km=plen(pts)/1000;
return{id:'j'+i,driverId:d.id,from,to,k,pts,km:+km.toFixed(1),dep:NOW+(hot?42+(i*7)%40:15+Math.floor(rnd()*280)),seats:Math.min(d.vehicle.seats-1,1+Math.floor(rnd()*4)),price:Math.round(km*3.6*(.85+rnd()*.3)),min:Math.round(km/28*60)}});
export const reservations=Array.from({length:220},(_,i)=>{const from=i<70?'Anna Nagar':pick(ZN);let to=i<70?'Guindy':pick(ZN);if(to===from)to='Adyar';return{id:'x'+i,from,to,seats:1+Math.floor(rnd()*3),status:rnd()>.25?'confirmed':'waiting'}});
export const history=Array.from({length:110},(_,i)=>({id:'h'+i,from:pick(ZN),to:pick(ZN),km:+(5+rnd()*15).toFixed(1),saved:Math.round(30+rnd()*90)}));
